In [1]:
!pip install numpy  # !-> 使用終端機

You should consider upgrading via the 'c:\users\tibame_ex14\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
type(np.zeros(3))

numpy.ndarray

In [6]:
np.zeros((2, 3), dtype=int)  # 預設為浮點數

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [9]:
np.empty((3, 3))  # 產生沒有意義的數字

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.54932307e-321],
       [1.78019082e-306, 0.00000000e+000, 2.54639495e-313]])

In [10]:
np.full(3, 255)

array([255, 255, 255])

In [11]:
np.random.rand(2, 5)  # 產生0~1的亂數

array([[0.45015333, 0.68188528, 0.13690318, 0.31548138, 0.18079456],
       [0.83504865, 0.54334698, 0.00993224, 0.2354261 , 0.34571198]])

In [13]:
np.random.randint(low=2, high=8, size=(2, 3), dtype=int)  # 產生2~8之間的亂數

array([[3, 4, 5],
       [2, 5, 2]])

In [3]:
test_arr = np.array([[2, 4, 4],
                     [4, 3, 2]])
test_arr

array([[2, 4, 4],
       [4, 3, 2]])

In [4]:
test_arr.ndim  # 幾維

2

In [5]:
test_arr.shape  # 幾列幾欄

(2, 3)

In [6]:
test_arr.size  # 總共多少個值

6

In [18]:
np.random.randint(low=2, high=8, size=(2, 3), dtype=int).shape

(2, 3)

In [19]:
np.random.randint(low=2, high=8, size=(2, 3), dtype=int).size

6

In [20]:
np.random.randint(low=2, high=8, size=(2, 3), dtype=int).ndim

2

In [21]:
arr = np.random.randint(low=2, high=8, size=(2, 3), dtype=int)
arr

array([[3, 6, 6],
       [6, 3, 6]])

In [22]:
arr.reshape((3, 2))

array([[3, 6],
       [6, 6],
       [3, 6]])

In [23]:
arr.reshape((3, -1))  # 值不好判斷時,輸入-1自動判別

array([[3, 6],
       [6, 6],
       [3, 6]])

In [ ]:
1,2,3,4,5,6,7,8,d,d,f,s,g,j,d,w,z,c,g,r,42,1,2,3,4,5,6,7,8,d,d,f,s,g,j,d,w,z,c,g,r,42
arr.reshape((-1, 10))

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [25]:
arr.mean()  # 風格偏向物件導向

3.5

In [26]:
np.mean(arr)  # 風格偏向函數導向

3.5

In [27]:
arr.max()

6

In [28]:
arr.min()

1

In [29]:
np.median(arr)  # 中位數,偶數個無解

3.5

In [30]:
help(np.median)

Help on function median in module numpy:

median(a, axis=None, out=None, overwrite_input=False, keepdims=False)
    Compute the median along the specified axis.
    
    Returns the median of the array elements.
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : {int, sequence of int, None}, optional
        Axis or axes along which the medians are computed. The default
        is to compute the median along a flattened version of the array.
        A sequence of axes is supported since version 1.9.0.
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output,
        but the type (of the output) will be cast if necessary.
    overwrite_input : bool, optional
       If True, then allow use of memory of input array `a` for
       calculations. The input array will be modified by the call to
       `med

In [10]:
np.percentile(arr, 50, method='higher')  # 百分位數取中間值，遇偶數個使用interpolation指定高還低
# np.percentile(arr, 50, interpolation='higher')

4

In [35]:
help(np.percentile)

Help on function percentile in module numpy:

percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)
    Compute the q-th percentile of the data along the specified axis.
    
    Returns the q-th percentile(s) of the array elements.
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    q : array_like of float
        Percentile or sequence of percentiles to compute, which must be between
        0 and 100 inclusive.
    axis : {int, tuple of int, None}, optional
        Axis or axes along which the percentiles are computed. The
        default is to compute the percentile(s) along a flattened
        version of the array.
    
        .. versionchanged:: 1.9.0
            A tuple of axes is supported
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output,
     

In [36]:
arr * 2

array([ 2,  4,  6,  8, 10, 12])

In [37]:
arr + 10

array([11, 12, 13, 14, 15, 16])

### 標準差 $\sigma = \sqrt{\frac{1}{n} \sum_{i=1}^n (x_i-\mu)^2}$

In [38]:
mu = arr.mean()

In [39]:
arr - mu

array([-2.5, -1.5, -0.5,  0.5,  1.5,  2.5])

In [40]:
arr.sum()  # 加總

21

In [44]:
np.power((arr - mu), 2)  # 次方

array([6.25, 2.25, 0.25, 0.25, 2.25, 6.25])

In [45]:
np.power((arr - mu), 2).mean()

2.9166666666666665

In [46]:
np.sqrt(np.power((arr - mu), 2).mean())  # 開根號

1.707825127659933

In [47]:
arr.std()  # 標準差

1.707825127659933

In [48]:
np.random.normal(0, 1, 10)  # 常態分佈陣列

array([ 0.34438054,  0.25616739,  1.14842284,  0.83795458, -0.47179853,
        1.28399599,  0.16713383, -0.56153994,  1.31188664, -0.01999242])

In [49]:
arr

array([1, 2, 3, 4, 5, 6])

In [50]:
arr > 3

array([False, False, False,  True,  True,  True])

In [51]:
~(arr > 3)  # 等同arr <= 3,反向表示

array([ True,  True,  True, False, False, False])

In [53]:
print(arr > 2)
print(arr < 5)
print((arr > 2) & (arr < 5))

[False False  True  True  True  True]
[ True  True  True  True False False]
[False False  True  True False False]


In [54]:
print(set([3, 4, 5, 6]))
print(set([1, 2, 3, 4]))

{3, 4, 5, 6}
{1, 2, 3, 4}


In [55]:
set([3, 4, 5, 6]) & set([1, 2, 3, 4])  # 交集

{3, 4}

In [56]:
set([3, 4, 5, 6]) | set([1, 2, 3, 4])  # 聯集

{1, 2, 3, 4, 5, 6}

In [57]:
set([3, 4, 5, 6]) - set([1, 2, 3, 4])  # 差集

{5, 6}

In [58]:
set([1, 2, 3, 4]) - set([3, 4, 5, 6])  # 差集

{1, 2}

In [59]:
(arr > 2) | (arr < 5)  # 聯集

array([ True,  True,  True,  True,  True,  True])

In [60]:
(arr > 2) ^ (arr < 5)  # 補集

array([ True,  True, False, False,  True,  True])

In [61]:
(arr > 2) & (arr < 5)  # 交集

array([False, False,  True,  True, False, False])

In [62]:
~(arr > 2) & ~(arr < 5)

array([False, False, False, False, False, False])